Updated Ruby-Installer

diff --git a/Ruby-Installer b/Ruby-Installer
--- a/Ruby-Installer
+++ b/Ruby-Installer
@@ -8,7 +8,7 @@
 #	Script original
 #
 #
-#	[ Credits to my freind Abhackeroficcial ] 
+#[ Credits to my freind github.com/Abhackeroficcial ] 
 #
 #
 # 
@@ -19,91 +19,32 @@
 #
 # Colores 
 AGUA="\e[2;50;36m" 
-WHITE="\e[0;50;37m"                                         
 RED="\e[0;50;91m"            
 GREEN="\e[0;50;32m"   
 YELOW="\e[0;50;33m"
 XH='\e[7;107;31m'
 FORT="\e[0m"
+ARCH=$(dpkg --print-architecture)
 #
-[ -x $PREFIX/bin/axel ] && pkg install axel -y &>/dev/null # installed Axel
+[[ ! -f $(type -P wget2) ]] && printf "[ wget2 not installed ]" && exit 1
 function installruby()
-{
-	
-	
-	sleep 0.3
-	ARR=$(dpkg --print-architecture)
-	if [[ $ARR = "arm" ]]
-	then
-		ARM="arm.deb"
-		echo -e "${GREEN}(✓) ${AGUA}You architecture ${YELOW}$ARR ${FORT}\n"
-		echo -e "\n${XH}  Wait for the download  ${FORT}"
-		axel -q https://github.com/abhackerofficial/abhacker.repo/raw/master/dists/abhacker/main/binary-arm/ruby.deb
-		apt install -y ./ruby.deb &>/dev/null
-		rm -rf ruby.deb
-		sleep 1
-		DPKG
-
-	elif [[ $ARR = "aarch64" ]]
-	then
-
-		echo -e "\n${GREEN}(✓) ${AGUA}You architecture ${YELOW}$ARR ${FORT}"
-		ARRCH="aarch64.deb"
-		echo -e "\n${XH}  Wait for the download  ${FORT}"
-		axel -q  https://github.com/abhackerofficial/abhacker.repo/raw/master/dists/abhacker/main/binary-aarch64/ruby.deb 
-		apt install -y ./ruby.deb &>/dev/null
-		rm -rf ruby.deb
-		sleep 1
-		DPKG
-	else
-		echo -e "\n${RED}[!] ${AGUA} Architecture not found ${RED}[!]${FORT}\n"
+{	printf "${XH}[ Downloading ruby for Termux ]$FORT\n\n"
+	case $ARCH in
+		arm|aarch64|i686)
+			wget2 --progress=bar --tries=20 https://github.com/RaulXH/Ruby-for-Termux/blob/main/ruby_2.7.2-${ARCH}.deb?raw=true -O "ruby_2.7.2-${ARCH}.deb"
+		apt install "./ruby_2.7.2-${ARCH}.deb" -y
+		rm -rf ruby_2*
+		;;
+	*)
+		printf "\n${RED}[ Architecture not found ] ${FORT}\n"
 		exit 1
-	fi
+		;;
+	esac
 
 
 }
-
-function DPKG()
-{
-	declare -r RUTA="/data/data/com.termux/files/usr/var/lib/dpkg/status"
-	# verificacion 
-	#
-	grep   -n  -q 'Package: ruby' $RUTA 
-	until [[ $? -eq 0 ]]
-	do
-		exit 0
-	done
-	#
-	LINENUMER=$(grep   -n  'Package: ruby' $RUTA | awk -F: '{print $1}')
-
-	PESO=$(($LINENUMER+2))
-	TERMUX=$(($LINENUMER+3))
-	VERSION=$(($LINENUMER+5))
-	#  cambiando linea
-	KEN=$(dpkg --print-architecture)
-	# Iniciando persistencia
-	if [[ $KEN = 'aarch64' ]]
-	then
-	#
-	#
-		echo -e "\n${GREEN}| ${WHITE}Installed ruby ​​correctly $KEN ${GREEN}|${FORT}\n"
-		sleep 1
-		sed -i -e "${VERSION}c Version: 3.0.1-1" -e "${PESO}c Installed-Size: 29292" -e "${TERMUX}c Maintainer: @termux" $RUTA	
-
-	else
-		echo -e "\n${GREEN}| ${WHITE}Installed ruby ​​correctly $KEN ${GREEN}|${FORT}\n"
-		sleep 1
-		sed -i -e "${VERSION}c Version: 3.0.1-1" -e "${PESO}c Installed-Size: 28496" -e "${TERMUX}c Maintainer: @termux" $RUTA
-		exit 0
-	fi
-}
-
-
-
 if  [[  -f $PREFIX/bin/ruby ]]
 then
-	#
-	# Si ruby existe y no esta la version 2.7.2
 	#
 	VERSION=$(ruby --version | awk '{print $2}')
 	if [[ ${VERSION%.*} =~ "2.7" ]]
@@ -118,9 +59,6 @@ then
 		
 	fi
 else
-	#
-	# Ruby no existe e Instala
-	#
 	sleep 2
 	installruby
 fi
